version: '3.8'

services:
  lookcerto-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_KEY=${API_KEY}
    container_name: lookcerto_production
    ports:
      - "3030:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - lookcerto-network

networks:
  lookcerto-network:
    driver: bridge
