version: '3.8'

services:
  lookcerto-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_KEY=${API_KEY}
        - MINIO_ENDPOINT=${MINIO_ENDPOINT}
        - MINIO_REGION=${MINIO_REGION}
        - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
        - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    container_name: lookcerto_production
    ports:
      - "3030:80"
    environment:
      - NODE_ENV=production
      - API_KEY=${API_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}
    restart: always
    networks:
      - lookcerto-network

networks:
  lookcerto-network:
    driver: bridge